project:
  type: website
  resources: assets
  output-dir: docs

website:
  title: "Rohan Devraj"
  navbar: 
    background: light
    logo: "assets/gtlogo5.png"
    foreground: dark
    left:
      - href: index.qmd
        text: about
      - projects.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/rohan-devraj-8646b1259/
        target: _blank
      - icon: github
        href: https://github.com/rdevraj3105
        target: _blank
      - icon: file-earmark-person
        href: assets/Rohan_Devraj_Resume-11:24.pdf
        target: _blank



format:
  html:
    theme: 
      light: yeti
      dark: darkly
     # - custom.scss
    css: styles.css
    toc: true



